swagger:
  version: 1.0.0
  title: ASK-Sahayak REST API
  description: this application provides the ASK-Sahayak Rest API
  contact: srikanthchebrolu3333@gmail.com
  contextPath:

server:
  contextPath: /asksahayak-service/api/v1
  port: ${PORT:8080}